# Site Settings
lang                : "en"
title               : "PISM"
tagline             : "Parallel Ice Sheet Model"
name                : &name "The PISM Authors"
description         : "Website for PISM, the Parallel Ice Sheet Model"
baseurl             : "" #/pism.github.io
url                 : "https://www.pism.io"
favicon             : "/favicon.ico"
gh_repository       : &gh_repo "https://github.com/pism"
gh_sponsor          : #
theme               : "bulma-clean-theme"
theme_color         : "#216778"
permalink           : "pretty"
fixed_navbar        : "top"
#hide_share_buttons  : true
footer_menu         : #example_footer_menu

pagination:
  enabled: true
  per_page: 5
  sort_reverse: true
  permalink: '/:num/'
  title: ':title'
  trail:
    before: 5
    after: 5

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: #my_disqus_shortname

# SEO Related
google_site_verification: #"SLng37Ih9dWmNOEhkLiKjYsUUdPQ3dRDW3-O6fYQru4"

# Analytics
google_analytics: #"UA-141242006-1"

# Site Author
author: 
  name     : *name
  email    : "uaf-pism@alaska.edu"
  facebook : &facebook "UAF.GI"
  github   : "pism"
  slack    : "https://join.slack.com/t/uaf-pism/shared_invite/enQtODc3Njc1ODg0ODM5LThmOTEyNjEwN2I3ZTU4YTc5OGFhNGMzOWQ1ZmUzMWUwZDAyMzRlMzBhZDg1NDY5MmQ1YWFjNDU4MDZiNTk3YmE"

# Social Sharing
logo            : "/img/pism_logo_transp.png"
facebook:
  username      : *facebook
  publisher     : #
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type          : Organization # Person or Organization (defaults to Person)
  name          : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://www.facebook.com/UAF.GI/"
    - *gh_repo

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude:
  - Gemfile
  - Gemfile.lock
  - docker/
  - usersmap/restore/
  - vendor/
  - pism.github.io.sublime-project
  - pism.github.io.sublime-workspace

livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: *name
      layout: post
      show_sidebar: true

markdown: kramdown
highlighter: rouge
